apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..name" . }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  KUBECONFIG: {{ .Values.config.KUBECONFIG | default "" | quote }}
  LISTEN_PORT: {{ .Values.config.LISTEN_PORT | default "8080" | quote }}
  UPDATE_INTERVAL: {{ .Values.config.UPDATE_INTERVAL | default "60" | quote }}
  DAYS_LEFT_CRITICAL_THRESHOLD: {{ .Values.config.DAYS_LEFT_CRITICAL_THRESHOLD | default "3" | quote }}
  DAYS_LEFT_WARN_THRESHOLD: {{ .Values.config.DAYS_LEFT_WARN_THRESHOLD | default "29" | quote }}